use 3i_in10;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS pizzas;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS pizza_ingredients;
DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS sizes;

DROP PROCEDURE IF EXISTS get_orders_average;

SET FOREIGN_KEY_CHECKS = 1;